apiVersion: v1
kind: Service
metadata:
  name: ak-api-001
  annotations:
    # create ILB instead of ELB; this functionality predates the PLS functionality
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: ak-kube-pls-003
    service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: aks-subnet
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address-count: "1"
    # The following IP address must be available in pls-subnet
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address: 10.224.10.10
    service.beta.kubernetes.io/azure-pls-fqdns: "akfqdn001"
    service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
    service.beta.kubernetes.io/azure-pls-visibility: "*"
    service.beta.kubernetes.io/azure-pls-auto-approval: "YOUR_SUBSCRIPTION_ID"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080